/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119074-gf47c8bca2c-20250330"
#endif /* AVUTIL_FFVERSION_H */
